spring:
  application:
    name: calculo
  rabbitmq:
    addresses: rabbitmq:5672
server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true