spring:
  application:
    name: servicioexterno

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true